descriptions = {
    "first party collection use": "Privacy practice describing data collection or data use by the company/organization owning the website or mobile app.",
    "personal information type": "The category of information that is collected or tracked by the company/organization",
    "financial": "Financial information, such as credit/debit card data, other payment information, credit scores, etc.",
    "health": "Health Information, such as information about health conditions, prescriptions, medication, as well as health monitoring data, e.g., heart rate, step count, activity level, etc.",
    "contact": "Contact Information, such as name, email address, phone number, street address, etc.",
    "location": "Geo-location information (e.g., user's current location) regardless of granularity, i.e., could be exact location, ZIP code, city-level.",
    "demographic": "Demographic Information, e.g., gender, age, occupation, education, etc.",
    "personal identifier": "Identifiers that uniquely identify a person,e.g., SSN, driver's license number, etc.",
    "user online activities": "The user's online activities on the first party website/app or other websites/apps, e.g., pages visited, time spent on pages, general user behavior online, etc.",
    "user profile": "The user’s profile on the first-party website/app and its contents, e.g., data in user profile, data that user uploaded to website, user comments, user profile preferences, etc. This is common for websites/apps where users can create an account or profile, e.g., on twitter, youtube, Facebook, Amazon, etc.",
    "social media data": "User profile and data from a social media website/app or other third party service to which the user gave the first party access, e.g., by connecting with Facebook, twitter, or other services. Exchanged data may include user profile, photos, comments, friends, etc.",
    "ip address and device ids": "Permanent (e.g., device IDs, MAC address) or temporary (e.g., IP address) identifiers needed to establish a connection for the current browsing session.",
    "cookies and tracking elements": "Identifiers locally stored on user's device by the company/organization or third-parties including cookies, beacons, or similar that are commonly used to uniquely identify users, but that are not essential to establish a connection with the user’s device or to provide a service.",
    "computer information": "he type of operating system (OS) or web browser that the user uses, or similar computer or device information.",
    "survey data": "Any data that is collected through surveys",
    "generic personal information": "No specific type of information is mentioned, but the policy talks about “personal information” or “personal identifiable information” in general.",
    "purpose": "The purpose of collecting or using user information",
    "basic service/feature": "Provide a service that the user explicitly requests and that is part of the website/app's basic service or functionality. Examples are watching a video, reading an article, making a purchase, creating an account, contacting the company, etc.",
    "additional service feature": "Provide a service that the user explicitly requests but that is not a necessary part of the website/app's basic service. Additional services/features may enhance user experience or add convenience but require additional data, e.g., social media integration, comments, blog participation, a store finder that needs location information, etc.",
    "advertising": "To show ads that are either targeted to the specific user or not targeted.",
    "marketing": "To contact the user to offer products,services, or other promotions (e.g., send marketing emails, calling or texting user with marketing messages). Marketing typically requires the use of contact information.",
    "analytics research": "For understanding the website/app’s audience, improving the website/app, inform company strategy, or general research.",
    "personalization/customization": "For providing user with a personalized experience, e.g., by allowing to arrange how the website/app looks, based on the user’s preferences or language, etc.",
    "service operation and security": "For website/app operation and security, enforcement of terms of service, fraud prevention, protecting users and property, etc.",
    "legal requirement": "For compliance with legal obligations, e.g., regulations, government data requests, government retention requests, law enforcement requests in general, etc.",
    "merger acquisition": "If company/organization merges or is acquired it transfers users' information to another company/organization.",
    "choice type": "The type of user choice or privacy control options available to users.",
    "dont use service feature": "Only option is not to use the feature or service.",
    "opt in": "User must consent before data can be collected or used",
    "opt out link": "Link provided in privacy policy, on website, in mobile app, or in email, etc.",
    "opt out via contacting company": "Must contact company via email, phone, or postal mail to opt-out.",
    "first party privacy controls": "Website/app provides user settings for privacy configuration.",
    "third party privacy controls": "Choices provided by a third party (e.g., privacy settings on social media site) or industry (e.g., AdChoices Opt-out).",
    "browser device privacy controls": "Policy suggests the use of browser or mobile device’s privacy settings, e.g., to block trackers or cookies, activate Do-Not-Track, disable location sharing, clear history, etc.",
    "third party sharing collection": "Choices apply to collection only",
    "third party entity": "The third-party involved in the data practice.",
    "unnamed third party": "The third party is not explicitly named, i.e., it is just generically referred to as \"third-party,\" \"partner,\" or similar.",
    "named third party": "The third party is explicitly named (e.g. Facebook) or at least characterized (e.g., “advertising partner” or “data broker”).",
    "other part of company affiliate": "Data is made available to other parts of the company/organization, e.g., it is shared with other services, apps, or websites operated by the company, could also be data exchange between online and offline company units (e.g. physical stores)",
    "other users": "The third-party involved are other users of the first party website or mobile app.",
    "public": "User information is made public or can be obtained from public sources.",
    "user choice control": "Practice that describes general choices and control options available to users.",
    "user access": "Privacy practice that allows users to access, edit or delete the data that the company/organization has about them.",
    "edit and deletion": "Privacy practice that allows users to access, edit or delete the data that the company/organization has about them.",
    "data retention": "Privacy practice specifying the retention period for collected user information.",
    "retention period": "Description of the retention period, i.e., how long data is stored.",
    "indefinitely": "Collected user information is retained indefinitely.",
    "limited": "Data is deleted, anonymized, or aggregated at some point, but no specific retention period is stated, e.g., “only stored as long as needed to perform requested service” or “as required by legal obligations.”",
    "stated period": "Collected user information is deleted, anonymized or aggregated after a specific time period, e.g., “activity data is anonymized after 30 days.”",
    "retention purpose": "The purpose to which the retention practice applies (may be “unspecified”).",
    "perform service": "Collected user information is only stored as long as it is needed to perform the requested service.",
    "data security": "Practice that describes how users’ information is secured and protected, e.g., from confidentiality, integrity, or availability breaches. Common practices include the encryption of stored data and online communications",
    "policy change": "The company/organization’s practices concerning if and how users will be informed of changes to its privacy policy, including any choices offered to users.",
    "change type": "For what type of changes to the website/app’s policy are users notified.",
    "no notification": "User is not notified of changes to the privacy policy.",
    "general notice in privacy policy": "The policy date is updated or information about the change is posted as part of the privacy policy site.",
    "general notice on website": "Users will be notified when visiting the main website, i.e., not only when looking at the privacy policy.",
    "personal notice": "Users will be personally informed about a privacy policy change, e.g., via email, text message or when logging into their account.",
    "do not track": "Practices that explain if and how Do Not Track signals (DNT) for online tracking and advertising are honored.",
    "international and specific audiences": "Specific audiences mentioned in the company/organization’s privacy policy, such as children or international users, for which the company/organization may provide special provisions.",

}